image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    visibility: public
vscode:
  extensions:
    - cyrusfirheir.twee3-language-tools
tasks:
  - before: |
      source /home/gitpod/lua51/bin/activate
      luarocks install moonscript
      luarocks install alfons
    init: |
      echo 'TODO: init app'
    command: |
      echo 'TODO: start app'