name: Publish

on:
  release:
    types: [published]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Prepare directories
        run: |
          ls .
          mkdir ./dist
          mkdir ./dist/audio
          cp -r ./src/audio/* ./dist/audio/

      - name: Build game
        run: |
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego -o dist/index.html src
 
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: five-poems
          ITCH_USER: actuallydael
          PACKAGE: dist